### ISSUE TITLE
imagenet evaluation code?

### ISSUE THREAD

**Issue by hengck23** [sanghoon/pytorch_imagenet#2]
I am trying to do evaluation on image net for your model. Do you have code for that? or do you use the default pytorch code: https://github.com/pytorch/examples/tree/master/imagenet?

**Comment by sanghoon** [comment]
Hi @hengck23 

You can evaluate a model by running the script with the following options.
'--evaluate --multicrop'
The first one is to evaluate a model, and the second one is to do 10-crop testing.

You can specify a model binary with the '--resume' argument.

**Comment by hengck23** [comment]
thanks!
